<center><img width="25%" src="https://www.camaramirimdoce.sc.gov.br/media/noticia/resumo-da-sessao-10-06-2019-111.png?w=848&h=450&t=P&c=f0f0f0&q=80&v=2"></center>

---

<br>

# Biblioteca NumPy

<br>

# **<u>Sumário:</u>**
1. [Definição](#Definição)
2. [Matrizes](#Matrizes)
3. [Convertendo uma lista e uma tupla em um objeto de matriz](#Convertendo-uma-lista-e-uma-tupla-em-um-objeto-de-matriz)
4. [Dimensões em matrizes](#Dimensões-em-matrizes)
5. [Funções de criação de matriz](#Funções-de-criação-de-matriz)
    * np.linspace
    * np.arange
    * np.zeros
    * np.one
    * np.empty
6. [Tipos de dados](#Tipos-de-dados) 
    * Tipos de dados do objeto NumPy
    * Tipos de dados com códigos de caracteres
    * Tipos de dados estruturados

## Definição
[(Voltar para o sumário)](#Sumário:)

### NumPy , forma abreviada de Numerical Python, é uma biblioteca poderosa para trabalhar com arrays. Ele tem um objeto de matriz multidimensional e vários utilitários para trabalhar com essas matrizes. NumPy forma uma base para outras bibliotecas Python como Pandas , Matplotlib , Scikit-learn e Scipy . <br>

### O NumPy é uma alternativa às listas do Python porque supera as execuções mais lentas usando o objeto de matriz multidimensional para executar operações lógicas e matemáticas complexas. Isso significa que é mais rápido que as listas do Python na execução de operações complexas. <br>

### Instalação e Importação da biblioteca:
    Sintaxe:
    pip install numpy
    import numpy as np

### Documentação:
> https://numpy.org/doc/stable/index.html
> https://www.machinelearningnuggets.com/numpy-tutorial/

In [35]:
import numpy as np

## Matrizes
[(Voltar para o sumário)](#Sumário:)

### O NumPy ndarray é um objeto de matriz N-dimensional que armazena um grupo de tipos de dados semelhantes. Por padrão, cada elemento no ndarray é um objeto do tipo de dados object(dtype). <br>

### Criando objeto ndarray: <br>
#### Criamos um array NumPy com a função array(). Quando uma lista ou tupla do Python é passada para a função de array, ela é automaticamente convertida em um arquivo ndarray. Ele é acessado com indexação baseada em zero, como em arrays regulares. <br>
### A função array() aceita alguns parâmetros:
    numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

* object: Especifica o objeto, que pode ser uma lista, tupla, dicionário, etc.
* dtype: É usado principalmente quando estamos definidno os tipos de dados, portanto, é opcional. O NumPy determinará automaticamente o tipo apropriado necessário para manter o objeto de matriz se não o definirmos. 
* order:  Especifica o layout de memória da matriz. As ordens são 'K', 'C', 'F', 'A'.
* copy: Quando definido como verdadeiro, o objeto é copiado.
* ndmin: Especifica o número de dimensões que queremos que o array resultante tenha. ndmin também é usado para verificar as dimensões do array.
* subok: Quando definido como verdadeiro, as subclasses passarão. Caso contrário, a matriz resultante é forçada a ser uma matriz de classe base (padrão).

## Convertendo uma lista e uma tupla em um objeto de matriz 
[(Voltar para o sumário)](#Sumário:)

    Sintaxe:
    import numpy as np

    lista = np.array([n°, n°, n°, n°, n°, n°])
    tupla = np.array((n°, n°, n°, n°, n°, n°))

In [36]:
import numpy as np

lista = np.array([900, 200, 300, 99, 54, 80])
print("Esta é uma lista em array numpy:\n", lista)
print("Tipo: ", type(lista))

tupla = np.array((50, 60, 90, 105, 90.6, 30.8))
print("Esta é uma tupla na matriz numpy:\n", tupla)
print("Tipo: ", type(tupla))

Esta é uma lista em array numpy:
 [900 200 300  99  54  80]
Tipo:  <class 'numpy.ndarray'>
Esta é uma tupla na matriz numpy:
 [ 50.   60.   90.  105.   90.6  30.8]
Tipo:  <class 'numpy.ndarray'>


## Dimensões em matrizes 
[(Voltar para o sumário)](#Sumário:)

* Matrizes de dimensão zero (0-D) são valores na matriz.
        
        Sintaxe: array0D = np.array(n°)
        
* Matrizes unidimensionais (1-D) são as dimensões básicas da matriz. Eles contêm as matrizes 0-D como seus elementos.
        
        Sintaxe: array1D = np.array([n°, n°, n°, n°, n°])
        
* Matrizes bidimensionais (2-D) são matrizes com matrizes 1-D como seus elementos.

        Sintaxe: array2D = np.array([[n°, n°, n°, n°], [n°, n°, n°, n°]])
        
* Matrizes tridimensionais (3-D) são matrizes com matrizes 2-D, também chamadas de matrizes.
        
        Sintaxe:
        array3D_1 = np.array([array2D]) 
        
        ou
        
        array3D_2 = np.array([
           [[n°,n°,n°],[n°,n°,n°],[n°,n°,n°]],
           [[n°,n°,n°],[n°,n°,n°],[n°,n°,n°]],
           [[n°,n°,n°],[n°,n°,n°],[n°,n°,n°]]
           ])
           
* Uma matriz pode ter várias dimensões. Para especificar o número de dimensões, usamos o ndimparâmetro.
        
        Sintaxe: array_varias_dimensões = np.array([n°, n°, n°, n°], ndmin = n°_dimensões)

In [37]:
import numpy as np

# Matrizes de dimensão zero (0-D)
array0D = np.array(30)
print(array0D)
print("Dimensão: ", array0D.ndim)

#  Matrizes unidimensionais (1-D
array1D = np.array([30, 40, 60, 80, 10])
print(array1D)
print("Dimensão: ", array1D.ndim)

# Matrizes bidimensionais (2-D)
array2D = np.array([[20, 50, 60, 12], [10, 15, 24, 23]])
print(array2D)
print("Dimensão: ", array2D.ndim)

# Matrizes tridimensionais (3-D)
# a) Podemos passar uma matriz 2-D 
array3D_1 = np.array([array2D])
print(array3D_1)
print("Dimensão: ", array3D_1.ndim)

# b) ou cria-se uma
array3D_2 = np.array([
           [[1,2,3],[4,5,6],[7,8,9]],
           [[9,8,7],[6,5,4],[3,2,1]],
           [[1,2,3],[6,5,6],[7,8,9]]
           ])
print(array3D_2)
print("Dimensão: ", array3D_2.ndim)

# Várias dimensões
array_6dimensoes = np.array([1, 2, 3, 4], ndmin=6)
print(array_6dimensoes)
print("Dimensions :", array_6dimensoes.ndim)

30
Dimensão:  0
[30 40 60 80 10]
Dimensão:  1
[[20 50 60 12]
 [10 15 24 23]]
Dimensão:  2
[[[20 50 60 12]
  [10 15 24 23]]]
Dimensão:  3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [6 5 6]
  [7 8 9]]]
Dimensão:  3
[[[[[[1 2 3 4]]]]]]
Dimensions : 6


## Funções de criação de matriz 
[(Voltar para o sumário)](#Sumário:)

### 1) np.linspace: <br>
#### Precisa de pelo menos três argumentos (start,end,step). Cria uma matriz 1-D com um número especificado de valores espaçados igualmente entre os valores inicial e final. 
#### Step especifica o espaço entre os valores.
    Sintaxe: linspace_array = np.linspace(Valor_inicial, Valor_final, espaço_entre_inicial_final) 

In [38]:
import numpy as np

linspace_array = np.linspace(2., 5., 6) 
print(linspace_array)

[2.  2.6 3.2 3.8 4.4 5. ]


### 2) np.arange: <br>
#### Precisa de pelo menos três argumentos (start,end,step). Cria uma matriz 1-D com valores incrementais. 
#### Sua vantagem sobre a função do range() é que ela permite a geração de uma série de valores que não são inteiros. range() dá um erro se tentar fazer isso.
    Sintaxe: arange_array = np.arange(Valor_inicial, Valor_final, valor_incremental)
    
#### OBS: Se fornecer apenas um argumento para a função arange(), funcionará com: start = 0 e step = 1.

In [39]:
import numpy as np

arange_array = np.arange(1, 30., 4)
print(arange_array)

[ 1.  5.  9. 13. 17. 21. 25. 29.]


### 3) np.zeros: <br>
#### Cria uma matriz preenchida com zeros e com a forma especificada.
    Sintaxe: array_zeros = np.zeros((quantidade_matriz, n°linhas, n°colunas))

In [40]:
import numpy as np

# No caso desse código, o array é de três dimensões, com dimensões 2x3x3, ou seja, possui 2 "camadas" com 3 linhas e 3 colunas cada.
array_zeros = np.zeros((2, 3, 3))
print(array_zeros)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### 4) np.one: <br>
#### Cria uma matriz preenchida com uns e com a forma especificada.
    Sintaxe: array_zeros = np.ones((quantidade_matriz, n°linhas, n°colunas))

In [41]:
import numpy as np

array_uns = np.ones((2, 3, 3))
print(array_uns)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### 5) np.empty: <br>
#### É utilizada para criar um array com valores iniciais aleatórios, que podem ser diferentes a cada execução do código. 
#### O dtype é utilizada para definir o tipo de dado dos elementos.
    Sintaxe: array_empty = np.empty([n°linhas, n°colunas], dtype="Tipo de dados")

In [42]:
import numpy as np

# Um array de duas dimensões com 5 linhas e 5 colunas, preenchido com valores não inicializados.
# A opção "dtype=int" é utilizada para definir o tipo de dado dos elementos do array como inteiros.
array_empty = np.empty([5, 5], dtype=int)
print(array_empty)

[[1039033464        635         50          0          0]
 [         0          0          0          0         52]
 [1852990827  808348773  878850361  761409592 1650865509]
 [ 942683181  809053539 1630365239  862217570  879059250]
 [ 778449209 1952543859 1714451317  909259108  909337909]]


## Tipos de dados
[(Voltar para o sumário)](#Sumário:)

### NumPy tem uma variedade de tipos de dados escalares. Cada um de seus tipos de dados integrados possui um código de caractere que o identifica.

<br>

* i – o código do caractere é para números inteiros (int8, int16, int32, int64, intp).
* u – código de caractere para inteiros sem sinal (uint8, uint16, uint32, uint64).
* f – código de caractere para floats(float16, float32, float32).
* c – código de caracteres para floats complexos (complex64, complex128).
* S – código de caractere para string.
* O – código de caractere para o objeto.
* M – código de caractere para data e hora.
* b – código de caractere para booleano.
* U – código de caractere para string unicode.

<br>

        Sintaxe:bjeto = np.dtype('Caracter_n°tamanho')
        
<br>

### Os itens da matriz são objeto dtypes, onde cada objeto de tipo de dados possui um bloco de memória fixo em relação à matriz. Criamos o objeto dtypes com o construtor numpy.dtype()]. Este construtor recebe três parâmetros que são:

    Sintaxe: np.dtype(dtype, align=False, copy=False)
    
* Objeto (dtype): Representa o objeto para o qual queremos ser convertidos.
* Align: Pode ser definido como Verdadeiro ou Falso. Se definido como true, adicionará preenchimento para tornar o objeto igual a uma estrutura C.
* Copy: Gera uma cópia do objeto.

<br>

### Para verificar o tipo de dados de um objeto, usamos dtype como atributo:
    Sintaxe: objeto.dtype

In [43]:
# Observe que os tipos de dados criados são exatamente do tipo de dados do objeto NumPy.
import numpy as np

dtype_inteiro = np.dtype(np.int32) 
print(dtype_inteiro, "\n Tipo: ", dtype_inteiro.type)

dtype_complexos = np.dtype(np.complex128) 
print(dtype_complexos, "\n Tipo: ", dtype_complexos.type)

dtype_booleanos = np.dtype(np.bool_) 
print(dtype_booleanos, "\n Tipo: ", dtype_booleanos.type)

dtype_float = np.dtype(np.float32) 
print(dtype_float, "\n Tipo: ", dtype_float.type)

dtype_inteiro_sem_sinal = np.dtype(np.uint64)
print(dtype_inteiro_sem_sinal, "\n Tipo: ", dtype_inteiro_sem_sinal.type) 

int32 
 Tipo:  <class 'numpy.int32'>
complex128 
 Tipo:  <class 'numpy.complex128'>
bool 
 Tipo:  <class 'numpy.bool_'>
float32 
 Tipo:  <class 'numpy.float32'>
uint64 
 Tipo:  <class 'numpy.uint64'>


In [44]:
# Usando os códigos de caracteres
import numpy as np

dtype_inteiro = np.dtype('i4')
print(dtype_inteiro, "\n Tipo: ", dtype_inteiro.type)

dtype_float = np.dtype('f8')
print(dtype_float, "\n Tipo: ", dtype_float.type)

dtype_complexos = np.dtype('c16')
print(dtype_complexos, "\n Tipo: ", dtype_complexos.type)

dtype_inteiro_sem_sinal = np.dtype('u8')
print(dtype_inteiro_sem_sinal, "\n Tipo: ", dtype_inteiro_sem_sinal.type)

int32 
 Tipo:  <class 'numpy.int32'>
float64 
 Tipo:  <class 'numpy.float64'>
complex128 
 Tipo:  <class 'numpy.complex128'>
uint64 
 Tipo:  <class 'numpy.uint64'>


### Criando tipos de dados estruturados: <br>
#### Um tipo de dados estruturado é uma coleção de campos onde cada campo tem um nome, um tipo de dados e um deslocamento de byte. O campo de tipo de dados pode ser qualquer tipo de dados NumPy enquanto NumPy determina automaticamente o deslocamento de bytes, mas você pode especificá-lo.<br>
* Criando uma lista de tuplas onde cada campo tem uma tupla. Cada tupla terá o formato (fieldname, datatype, shape).
    * fieldname = nome do campo
    * datatype = tipo de dados
    * shape = forma é opcional
OBS: Se deixar em fieldname branco, será automaticamente atribuído um nome padrão do campo f#, onde o # é o índice do campo contando a partir do índice 0.

<br>

* Criando uma lista de especificações dtype separadas por vírgula. O fieldnames e o deslocamento de byte são atribuídos automaticamente. Os nomes dos campos recebem nomes f0, f1, f2...de acordo com o índice do campo. 

<br>

* Criando um dicionário de matrizes de parâmetros de campo. Teremos pelo menos quatro chaves para usar, que são:
    * names:  deve ter uma lista de nomes de campos [].
    * formats: deve ser uma lista dtypes do mesmo tamanho.
    * offsets (opcional): O valor deve ter uma lista de deslocamentos de bytes inteiros.
    * itemsize (opcional): O valor deve ser um inteiro descrevendo o tamanho total do arquivo dtype.

In [45]:
import numpy as np

# tipos de dados estruturados com uma lista de tuplas
lista_tuplas_1 = np.dtype(([('name', 'S20'), ('age', np.int16), ('marks', 'f4', (2, 2))]))
print(lista_tuplas_1)

# dtypes separados por vírgula
lista_tuplas_2a = np.dtype('S20, int16, f4')
print(lista_tuplas_2a)
 
lista_tuplas_2b = np.dtype('3int16, float32, (2, 3)float64')
print(lista_tuplas_2b)

# Criando um dicionário de matrizes de parâmetros de campo
lista_tuplas_3 = np.dtype({'names': ['name', 'salary'],
          'formats': ['i4', 'f4'],
          'offsets': [0, 4],
          'itemsize': 12})
print(lista_tuplas_3)

[('name', 'S20'), ('age', '<i2'), ('marks', '<f4', (2, 2))]
[('f0', 'S20'), ('f1', '<i2'), ('f2', '<f4')]
[('f0', '<i2', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))]
{'names': ['name', 'salary'], 'formats': ['<i4', '<f4'], 'offsets': [0, 4], 'itemsize': 12}


In [46]:
import numpy as np

# criar uma matriz vazia com 10 linhas e 1 coluna, onde 
arr = np.empty((10,1), dtype=np.dtype([('a','f8'),('b','S10')]))

# preencha a matriz com valores aleatórios
# preenche cada linha com um valor aleatório para o campo 'a' (um número inteiro de 0 a 9)
# e uma string para o campo 'b' (com o valor 'string' seguido pelo número da linha).
for i in range(10):
    arr[i] = (i, 'string ' + str(i))

print(arr)

[[(0., b'string 0')]
 [(1., b'string 1')]
 [(2., b'string 2')]
 [(3., b'string 3')]
 [(4., b'string 4')]
 [(5., b'string 5')]
 [(6., b'string 6')]
 [(7., b'string 7')]
 [(8., b'string 8')]
 [(9., b'string 9')]]


## Matrizes estruturadas
[(Voltar para o sumário)](#Sumário:)

Estas são matrizes cujo tipo de dados é estruturado.

In [47]:
import numpy as np

structured_arr = np.array([('John', 23, 100.4), ('Mercy', 30, 58.3)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
print(structured_arr)
print(structured_arr.dtype) 

[('John', 23, 100.4) ('Mercy', 30,  58.3)]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]


In [48]:
import numpy as np

model = ['Bentley', 'Toyota', 'Audi', 'Ford']
weight = [1400.8, 2500, 1600, 1700]
color = ['Blue', 'Green', 'White', 'Black']
speed = [240, 180, 300, 260]
vehicle_data = np.zeros(4, dtype={'names': ['model', 'weight', 'color', 'speed'],
                 'formats': ['U10', 'f8', 'U10', 'f8']
                 })
vehicle_data['model'] = model
vehicle_data['weight'] = weight
vehicle_data['color'] = color
vehicle_data['speed'] = speed

print("Data: \n", vehicle_data)
print("All vehicle Models:\n", vehicle_data['model'])

Data: 
 [('Bentley', 1400.8, 'Blue', 240.) ('Toyota', 2500. , 'Green', 180.)
 ('Audi', 1600. , 'White', 300.) ('Ford', 1700. , 'Black', 260.)]
All vehicle Models:
 ['Bentley' 'Toyota' 'Audi' 'Ford']
